### ISSUE TITLE
Sound too loud

### ISSUE THREAD

**Issue by maxdippel** [carlkuesters/carl-bot#2]
I have to have the bot on 3% volume all the time.

**Comment by destroflyer** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in https://github.com/carlkuesters/carl-bot/commit/8e2ad363e8823904feef7cb29f1abaa86bfbbe6f. You should now be able to have the bot at 100% at all times.

With best regards and have an awesome day,
the developer team of carl-bot
