### ISSUE TITLE
hi^^

### ISSUE THREAD

**Issue by maxdippel** [carlkuesters/carl-bot#3]
Add Maxi's _hi_ as sound command.

**Comment by destroflyer** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in https://github.com/carlkuesters/carl-bot/commit/8e2ad363e8823904feef7cb29f1abaa86bfbbe6f.

With best regards and have an awesome day,
the developer team of carl-bot

**Comment by maxdippel** [comment]
Ideally, it would automatically play every time someone joins the voice chat

**Comment by destroflyer** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in the latest commits and is already live! The bot will now:
- Play a Maxi "Hi" sound when Maxi writes hi (including variatons of "hi", "HI", "hi^^", "hi ^^", etc.)
- Play a Maxi "Hi" sound when someone joins the voice channel of the bot
- Play a Maxi "Hi" sound when the bot itself joins a voice channel
- Be able to play stuff without the commander being in a voice channel - It will select the most appropriate voice channel and play it there (usually the channel of the commander, the channel of the bot or simply the one with the most members in it)

With best regards and have an awesome day,
the developer team of carl-bot
