### ISSUE TITLE
bot should be nice to other bots

### ISSUE THREAD

**Issue by maxdippel** [carlkuesters/carl-bot#4]
don't ignore other bots :'(

**Comment by destroflyer** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in 20ea91bc6ada8f9cd6e45a84010d82d2ca029438 along with some other cool new features like reacting to "heycarl" or "wave" emotes.

With best regards and have an awesome day,
the developer team of carl-bot
