### ISSUE TITLE
youtube with start time

### ISSUE THREAD

**Issue by maxdippel** [carlkuesters/carl-bot#5]
bot can't play youtube videos with starting time (e.g. &t=15 at the end of the url)

**Comment by destroflyer** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in 935ee77 and is already live! You should now be able to define time ranges on play commands:
- !play [searchTermOrUrl] #5 (Starts at 5 seconds)
- !play [searchTermOrUrl] #5-9 (Starts at 5 seconds and stops at 9)
- !play [searchTermOrUrl] #2:10 (Starts at 2 minutes and 10 seconds)
- !play [searchTermOrUrl] #2:10-3:40 (Starts at 2 minutes and 10 seconds and ends at 3 minutes and 40 seconds)
- etc. - You can combine start and end position as you like including minute:second (if only one number is specified, it will be interpreted as seconds as seen by the examples above)

With best regards and have an awesome day,
the developer team of carl-bot
