### ISSUE TITLE
bot should be able to make decisions

### ISSUE THREAD

**Issue by maxdippel** [carlkuesters/carl-bot#6]
like !carl [a, b, c]

**Comment by carlkuesters** [comment]
Hello maxdippel,

thanks for opening this issue! We are always super excited to hear feedback from the community and try to give our best to offer a good user experience. People like you help us realizing this dream! ^_^

The problem you mentioned has been fixed in 49556ef160301fc06418cb5a238f59f6ee71e596 and is already live! You should now be able to let the bot choose between multiple options:

!choose option1, option2, option3, ... (comma-seperated, spaces do not matter)

The bot will choose a random one and post it to the according channel.

With best regards and have an awesome day,
the developer team of carl-bot
